[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'tyru/caw.vim'
[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'mxw/vim-jsx'
[[plugins]]
repo = 'tpope/vim-rhubarb'
[[plugins]]
repo = 'tomlion/vim-solidity'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'github/copilot.vim'
